spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.web=DEBUG
spring.http.multipart.enabled=true
spring.http.multipart.location= /Users/venkat/Downloads/this is test
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

