<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 5 Transitional//EN" 
"http://www.w3.org/TR/html4/loose.dtd">

<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="jakarta.tags.core" prefix="c"%>
<%@ page session="true"%>

<html>
<head>

<jsp:include page="../header.jsp"></jsp:include>

</head>
<body class="fixed-navbar sidebar-scroll">



	<jsp:include page="../PageTopBanner.jsp"></jsp:include>
	<jsp:include page="../PageLeftMenu.jsp"></jsp:include>

	<div id="wrapper">

		<div class="normalheader small-header">
			<div class="hpanel">
				<div class="panel-body">
					<h2 class="font-light m-b-xs">Manage Transactions</h2>
					<small>Import transaction files</small>
				</div>
			</div>
		</div>

		<div class="content">


			<jsp:include page="../showMessage.jsp"></jsp:include>


			<div class="row">
				<div class="col-sm-3">
					<div class="hpanel plan-box hyellow">
						<div class="panel-heading hbuilt text-center">
							<h4 class="font-bold">HDFC Statement</h4>
						</div>
						<div class="panel-body">
							<p class="text-muted">This template is in PDF format and generated by HDFC bank.</p>


							<a href="#" class="btn btn-warning btn-sm m-t-xs">Import File</a>
						</div>
					</div>
				</div>

				<div class="col-sm-3">
					<div class="hpanel plan-box hyellow">
						<div class="panel-heading hbuilt text-center">
							<h4 class="font-bold">Spendee</h4>
						</div>
						<div class="panel-body">
							<p class="text-muted">This template is exported from Spendee application.</p>

							<form:form action="/importTransactions/uploadAndReconcileTransactionFile" method="post" enctype="multipart/form-data">
								<div class="error-container">
									<input type="file" class="form-control" name="transactionFile" />
									<div class="hr-line-solid"></div>
									<button type="submit" class="btn btn-warning">Import</button>
								</div>
							</form:form>

						</div>
					</div>
				</div>

				<div class="col-sm-3">
					<div class="hpanel plan-box hyellow">
						<div class="panel-heading hbuilt text-center">
							<h4 class="font-bold">SBI Statement</h4>
						</div>
						<div class="panel-body">
							<p class="text-muted">This template is in PDF format and generated by SBI bank.</p>


							<a href="#" class="btn btn-warning btn-sm m-t-xs">Import File</a>
						</div>
					</div>
				</div>

				<div class="col-sm-3">
					<div class="hpanel plan-box hyellow">
						<div class="panel-heading hbuilt text-center">
							<h4 class="font-bold">KOTAK Statement</h4>
						</div>
						<div class="panel-body">
							<p class="text-muted">This template is in PDF format and generated by KOTAK bank.</p>


							<a href="#" class="btn btn-warning btn-sm m-t-xs">Import File</a>
						</div>
					</div>
				</div>
			</div>

			

		</div>





		<jsp:include page="../footer.jsp"></jsp:include>
	</div>

	<jsp:include page="../scripts.jsp"></jsp:include>




</body>
</html>